export const COLORS = {
    theme : '#FFFFFF',
    button: '#1F9CEF',
    introText: '#0F141A',
    loginTextInput : '#222B2E',
    loginText: '#11203D',
    registerTextInput : '#222B2E',
    textInputBorder: '#546471',
    label: '#222B2E',
    white: '#FFFFFF',
    lightgray: '#eee',
    cream : '#FEF5E7',
    black: '#000',
    green: '#229954',
    yellow:'yellow',
    orange:'orange',
    red : '#E50C25',
    overlayBG : '#0F141AB0',
    grayBG: '#F2F7FC',
    CircleBG: '#F6F8FC',
    ActiveSKUBorder: '#A5D8FA',
    activeSKUBg: '#F0F8FF',
    searchBorderColor:'#DCDCDC',
    green: '#36B152',
    sidemnuBorder: '#E9E2E2',
    tabtextColor: '#CCD6DE',
    tabbarBG:'#CCD6DE',
    DragBG: '#F7F9FA',
    checkboxBG: '#E6F0F8',
    dragboxBG: '#BEBEBE',
    uploadBG: '#ECF7FF',
    uploadedBG: '#D3EBFD',
    imageBorder: '#E0EBF3',
    profileProgressBG: '#fff5fa5c',
    homeBg: '#FFF5FA',
    chooseFileBG: '#F7F7F7'
}